const {counterFactory, limitFunctionCallCount, print}=require('./closures.js')
console.log("counterFactory")
console.log(counterFactory())
console.log(counterFactory().increment())
console.log(counterFactory().decrement(2))
console.log("limitFunctionCallCount")
let a =limitFunctionCallCount(print,6)
console.log(a)
console.log(a())