const {counterFactory, limitFunctionCallCount, print, cacheFunction,add}=require('./closures.js')
console.log("counterFactory")
console.log(counterFactory())
console.log(counterFactory().increment())
console.log(counterFactory().decrement(2))
console.log("limitFunctionCallCount")
let a =limitFunctionCallCount(print,6)
console.log(a)
console.log(a())
console.log("cacheFunction")
let b= cacheFunction(add)
console.log(b)
console.log(b(add))