const {counterFactory, limitFunctionCallCount, print, cacheFunction,print1}=require('./closures.js')
console.log("counterFactory")
console.log(counterFactory())
console.log(counterFactory().increment())
console.log(counterFactory().decrement(2))
console.log("limitFunctionCallCount")
let a =limitFunctionCallCount(print,6)
console.log(a)
console.log(a(1))
console.log(a(2))
console.log(a(3))
console.log(a(4))
console.log(a(5))
console.log(a(6))
console.log(a(7))
console.log("cacheFunction")
let b=cacheFunction(print1)
console.log(b)
b(2)
b(3)
console.log(b(2))